name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # ✅ Dependency Graph için gerekli izin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Verify repository structure
      run: ls -la  # ✅ Dosya yapısını kontrol eder
      
    - name: Build with Maven (Skip Tests)
      run: mvn -B package -DskipTests --file pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
